version: 2.1
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-firebase
          command: 'npm install --save-dev firebase-tools'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_module
      - run: BUILD_TIME=$(date '+%m/%d/%Y %X') npm run build
      - run:
          name: Install Firebase functions node_module
          command: '(cd ./functions; npm install)'
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN_PROD
      - run:
          name: Purging Cloudflare cache
          command: CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY CLOUDFLARE_API_EMAIL=$CLOUDFLARE_API_EMAIL npm run purge